### ISSUE TITLE
Implement DNS configuration 

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#67]
As per the CNI spec, this is an optional behavior.  https://github.com/appc/cni/blob/master/SPEC.md#result

**Comment by tomdee** [comment]
I'm not sure when or why we would want to supply DNS config?

**Comment by euprogramador** [comment]
Kubernetes manage internal dns cluster vis skydns,  containers should be able to access these services by resolving names dns skydns

**Comment by euprogramador** [comment]
guys,

cni configured the driver as follows:

/etc/cni/net.d/10-calico.conf 
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_authority": "masters.paas.cluster:2379",
    "log_level": "info",
    "ipam": {
       "type": "calico-ipam"
    }
}

and create pod test using image python http.server and executed command into container:

curl teste.default.svc.paas.cluster:8080

it works, ie dns is configured via Kubernetes not cni because of that is dns is optional. 

in my cluster works fine, without dns cni configuration.

**Comment by caseydavenport** [comment]
Yeah, I think this is a "move to DNS via CNI if and when k8s does it", so I'm going to close for now.
